### PR TITLE
Hariharan/unique names

### PR DESCRIPTION
**Pull request by hariharan-devarajan**
This PR Fixes #117 for creating unique names. I am using PID to distinguish file names.

### CODE REVIEW

**Comment by ChristopherHogan** [comment]
Could you please remove the license changes so they don't conflict with Kimmy's #113?

**Comment by hariharan-devarajan** [comment]
> Could you please remove the license changes so they don't conflict with Kimmy's #113?

Removed the license and fixed the conflicts.

**Comment by ChristopherHogan** [comment]
Can you add the PID to the `cmp` files you added in #110?

**Comment by hariharan-devarajan** [comment]
> cmp

I got the latest from the master. Now it has the getpid on all names.

**Review by ChristopherHogan — APPROVED** [review]

**Pull request merged**
